export const REQUEST_PRODUCTS = "REQUEST_PRODUCTS";
export const RECIEVED_PRODUCTS = "RECIEVED_PRODUCTS";
export const RECIEVE_FAILED = "RECIEVE_FAILED";
export const RECIEVE_SINGLE_PRODUCT = "RECIEVE_SINGLE_PRODUCT";